CREATE TABLE [dbo].[Passengers]
(
	[Id] BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	[Email] NVARCHAR(100) NULL UNIQUE,
	[Password] NVARCHAR(64) NULL,
	[FirstName] NVARCHAR(100) NOT NULL,
	[LastName] NVARCHAR(100) NOT NULL,
	[PassportNo] NVARCHAR(25) NOT NULL,
	[DateOfBirth] DATE NOT NULL
)
