CREATE TABLE [dbo].[Reservations]
(
	[Id] BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	[PassengerId] BIGINT NOT NULL REFERENCES Passengers(Id) ON DELETE NO ACTION,
	[ScheduleId] BIGINT NOT NULL REFERENCES Schedule(Id) ON DELETE NO ACTION
)
