CREATE TABLE [dbo].[Schedule]
(
	[Id] BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	[FlightId] NVARCHAR(10) NOT NULL REFERENCES Flights(Id) ON DELETE CASCADE,
	[DepartureDateTime] DATETIME NOT NULL,
	[ArrivalDateTime] DATETIME NOT NULL,
	[AircraftId] INT NULL REFERENCES Aircrafts(Id) ON DELETE SET NULL
)
